# Generated by Django 3.0.6 on 2020-05-16 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_auto_20200516_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_backref', to=settings.AUTH_USER_MODEL),
        ),
    ]
