# Generated by Django 3.0.6 on 2020-05-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0003_auto_20200516_1533'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
