# Generated by Django 3.0.6 on 2020-05-17 14:56

import auth_sys.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0004_auto_20200517_1753'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_sys.models.MyUserManager()),
            ],
        ),
    ]
