# Generated by Django 3.0.6 on 2020-05-21 15:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_sys', '0005_auto_20200517_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='QsarDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=150)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_sys.Organization')),
            ],
        ),
    ]
