# Generated by Django 3.0.6 on 2020-06-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qsardb',
            name='data',
        ),
        migrations.AddField(
            model_name='qsardb',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
