# Generated by Django 3.0.6 on 2020-06-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsar_db', '0002_auto_20200606_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qsardb',
            name='org',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='qsardb',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=150),
        ),
    ]
